CREATE TABLE category(
category_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name VARCHAR(255) NOT NULL,
discription VARCHAR(255)
);
Create TABLE supplier(
supplier_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name VARCHAR(255) UNIQUE NOT NULL,
cnpj VARCHAR(14) UNIQUE NOT NULL,
contact VARCHAR(255) UNIQUE,
active BOOLEAN DEFAULT(TRUE),
created_at TIMESTAMP,
updated_at TIMESTAMP
);

CREATE TABLE product(
product_id UUID  PRIMARY KEY,
name VARCHAR(255) NOT NULL,
sku VARCHAR(255) UNIQUE NOT NULL,
category_id INT NOT NULL,
dimension VARCHAR(255),
weight DECIMAL(10,2),
location VARCHAR(255),
minstock INT,
active BOOLEAN DEFAULT(TRUE),
created_at TIMESTAMP,
updated_at TIMESTAMP,
CONSTRAINT fk_product_category
  FOREIGN KEY(category_id) REFERENCES category(category_id)
);

CREATE TABLE product_supplier (
  product_supplier_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id UUID NOT NULL,
  supplier_id INT NOT NULL,
  buyprice DECIMAL(10,2),
  lead_time INT,
  minimal_qtd DECIMAL(10,2),
  active BOOLEAN DEFAULT(TRUE),
  created_at TIMESTAMP,
  updated_at TIMESTAMP,

  CONSTRAINT fk_product__product_supplier
    FOREIGN KEY(product_id) REFERENCES product(product_id) ON DELETE CASCADE,
  CONSTRAINT fk_supplier__product_supplier
    FOREIGN KEY(supplier_id) REFERENCES supplier(supplier_id) ON DELETE CASCADE
);
