CREATE TABLE category(
category_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name VARCHAR(255) NOT NULL,
discription VARCHAR(255)
);
Create TABLE supplier(
supplier_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name VARCHAR(255) NOT NULL,
cnpj VARCHAR(14) UNIQUE NOT NULL,
phone VARCHAR(14) UNIQUE NOT NULL,
email VARCHAR(255) UNIQUE NOT NULL,
cep VARCHAR(9),
address TEXT,
active BOOLEAN DEFAULT(TRUE),
created_at TIMESTAMP,
updated_at TIMESTAMP
);

CREATE TABLE product(
product_id UUID  PRIMARY KEY,
name VARCHAR(255) NOT NULL,
sku VARCHAR(255) UNIQUE NOT NULL,
category_id INT NOT NULL,
dimension VARCHAR(255),
weight DECIMAL(10,2),
location VARCHAR(255),
minstock INT,
active BOOLEAN DEFAULT(TRUE),
created_at TIMESTAMP,
updated_at TIMESTAMP,
CONSTRAINT fk_product_category
  FOREIGN KEY(category_id) REFERENCES category(category_id)
);

CREATE TABLE product_supplier (
  product_supplier_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product UUID NOT NULL,
  supplier INT NOT NULL,
  buyprice INT NOT NULL,
  lead_time INT NOT NULL,
  minimal_qtd INT NOT NULL,
  active BOOLEAN DEFAULT(TRUE),
  created_at TIMESTAMP,
  updated_at TIMESTAMP,

  CONSTRAINT fk_product__product_supplier
    FOREIGN KEY(product) REFERENCES product(product_id) ON DELETE CASCADE,
  CONSTRAINT fk_supplier__product_supplier
    FOREIGN KEY(supplier) REFERENCES supplier(supplier_id) ON DELETE CASCADE
);
